Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: firstName
        lastname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: lastName
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }